# GET http://localhost:3000/data/654d08883c3bd9333997c809


###


# POST http://localhost:3000/data/2
# Content-Type: application/json

# {
# }

# PUT http://localhost:3000/data/654d09ead97d39e40a860dbc/0

PUT http://localhost:3000/data/654d09ead97d39e40a860dbc/1
Content-Type: application/json

{
  "title": "isdfte",
  "text": "NEW"
}